
# *GUIA PARA INICIANTES. 1/3âš”ğŸ“œ_*
## *_Esse guia em especifico Ã© focado em explicar a criaÃ§Ã£o de personagem._*
![alt text](image.png)
## Pra que esse guia serve?âšœ
 ## *_-Esse guia consiste em ensinar minimamente sobre o jogo, para que os iniciantes possam se adaptar melhor ao estilo de gameplay de Deepwoken, pois Deepwoken gosta de dificultar qualquer coisas, atÃ© as minimas aÃ§Ãµes, punindo o jogador de alguma maneira._*
 # O que Ã© o Deepwoken?
![alt text](image-1.png)

 * ## *_Deepwoken Ã© um jogo no estilo â€œsouls-likeâ€ tendo um tipo extremamente dificil de gameplay, com DIVERSAS mecanicas e coisas para se fazer, o que acaba fazendo Deepwoken perder uma quantidade de player, outro motivo tambÃ©m Ã©: â€œSistema de perma-death/Morte permanenteâ€, esse sistema funciona da seguinte maneira: ao morrer 2 vezes na superficie, e uma vez nas profundezas (The Depths) vocÃª â€œobrigatoriamenteâ€ terÃ¡ que perder seu personagem, isso nÃ£o signfica que vocÃª nÃ£o poderÃ¡ mais jogar, mas sim que vocÃª voltarÃ¡ do zero, apenas para uma nova experiencia._*
 # CriaÃ§Ã£o de Personagem.
## (esse tÃ³pico vai de raÃ§as atÃ© origens.)
# --> RaÃ§as: 
![alt text](image-2.png)

## _*No Deepwoken, existem 12 raÃ§as diferentes, com estilos e aparÃªncias diferentes, aumentando o estlo do seu personagem.*_
# (Exemplos de raÃ§as)
## Canor
![alt text](image-3.png)
## Capra
![alt text](image-4.png)
## Ganymede
![alt text](image-5.png)
# NÃ£o gostei da minha raÃ§a, tem como mudar?
### -Sim, no deepwoken Ã© possivel mudar sua raÃ§a, por 150 robux (75 em promoÃ§Ã£o), tendo uma chance de pegar uma das 12 raÃ§as que Ã© possivel pegar normalmente, sendo da mais comum ou atÃ© a mais rara.
# Arma inicial:
## No Deepwoken, temos 3 categorias de armas, sendo elas:
- # Leves
  ![alt text](image-7.png)
  # MÃ©dias 
  ![alt text](image-6.png)
- # Pesadas 
  ![alt text](image-8.png)
- ### _(NÃ£o consegui a imagemğŸ˜­)_

 ## _Sendo as inicias: Espada, Stiletto/Estilete e Machado._
- ## *Leves*: Dano reduzido, porÃ©m sua velocidade de ataque Ã© aumentada, podendo ter um belo DPS, sendo dificil de dar parry contra esse tipo de arma.
  ![alt text](image-9.png)

- ## *MÃ©dias*: Dano e velocidade medianas, sendo o padrÃ£o de arma, bem â€œbalanceadoâ€
  ![alt text](image-10.png)

- ## *Pesadas*: Dano maior, porÃ©m menos velocidade de ataque, sendo perfeita para builds PvE, !
![alt text](image-11.png)
   # -Existe outros tipos de armas?
 ## _-Sim, uma variedade *IMENSA* de armas, porÃ©m sÃ³ algumas estÃ£o permitidas na criaÃ§Ã£o de personagem, como: LanÃ§as, Estilo de luta, Pistolas, Greatswords e Rapieiras._
![alt text](https://i.redd.it/j6jriymixcra1.gif)
# _Attunements_
## _-Da parte da criaÃ§Ã£o de personagens,e temos os *â€œAttunementsâ€* que se resume no que vocÃª pode controlar, sua magia, tendo mantras (sua habilidades)._
![alt text](image-12.png)

## Ether:
- ### Ether Ã© basicamente sua mana, o que vocÃª usa para sua magia.
- # E Quais sÃ£o os â€œAttunementsâ€?
### -Atualmente existem 7 attunements diferentes, sendo eles: Galebreath, Flamecharm, Frostdraw, Thundercall, Shadowcast, Ironsing e Bloodrend.
## Galebreath
![alt text](image-13.png)
### -Ã‰ a magia de controlar ventos, sendo bem versatil (pode ser habilitada desde o inÃ­cio do jogo)
## Flamecharm:
![alt text](image-14.png)
### -Ã‰ a magia capaz de controlar o fogo, causando danos de queimaÃ§Ã£o, e tambÃ©m bem explosiva.(pode ser habilitada desde o inicio do jogo)
## Frostdraw:
## ![alt text](image-15.png)
### -Magia capaz de controlar o gelo, sendo bastante forte desde o inicio do jogo.(pode ser habilitada desde o inicio do jogo)
## Thundercall:
![alt text](image-16.png)
### -Magia capaz de controlar raios, combinando com varios estilos de armas.(pode ser habilitada desde o inicio do jogo)
## Shadowcast:
![alt text](image-17.png)
### -Magia capaz de controlar as sombras, podendo mudar os Attunements de Frostdraw e Flamechar(NÃ£o pode ser habilitada na criaÃ§Ã£o de personagem, apenas durante o jogo, apÃ³s liberÃ¡ la no jogo, estarÃ¡ disponivel na criaÃ§Ã£o de personagem)
## Ironsing:
![alt text](image-18.png)
### -Magia capaz de manipular o ferro, sendo eficaz na maioria das coisas.(NÃ£o pode ser habilitada na criaÃ§Ã£o de personagem, apenas durante o jogo, apÃ³s liberala no jogo, estarÃ¡ disponivel na criaÃ§Ã£o de personagem)
## Bloodrend:
![alt text](image-19.png)
 ### -Sendo o mais novo  attunement, ele Ã© capaz de manipular o sangue.(NÃ£o pode ser habilitada na criaÃ§Ã£o de personagem, apenas durante o jogo, apÃ³s liberala no jogo, estarÃ¡ disponivel na criaÃ§Ã£o de personagem)
 # *-Eu posso iniciar um save sem um â€œattunementâ€?*
### Sim, vocÃª pode, e ainda terÃ¡ seus mantras, mas eles sÃ£o com base em seus status de forÃ§a e etcâ€¦ Ã‰ o que chamamos de â€œAttunementlessâ€
![alt text](image-20.png)
## -  Eu posso ter mais de um mantra?
 #### Sim, vocÃª pode, na criaÃ§Ã£o de personagem, vocÃª pode colocar atÃ© 2, porÃ©m durante o jogo, vocÃª pode ter simplesmente todos.

# *_Status e â€œShrine of Orderâ€_*
![alt text](image-21.png)

### _No Deepwoken, temos 6 status principais, sendo eles: **ForÃ§a, Fortitude, Agilidade, InteligÃªncia, Willpower (forÃ§a de vontade) e Charisma.** Isso sem contar os de armas e de Attunements._
![alt text](image-22.png)

### _ForÃ§a: Aumenta a penetraÃ§Ã£o de armadura, sendo o quanto vocÃª vai ignorar da armadura do oponente._

### _Fortitude: Aumenta sua vida, fazendo vocÃª aguentar mais ataques._

### _Agilidade: Aumenta sua velocidade de movimento, te fazendo vocÂªe ser capaz de correr ou subir em qualquer lugar._

### _InteligÃªncia: Aumenta seu ether, permitindo usar mais magias_

### _Willpower: Aumenta sua sanidade e Tempo_

### _Charisma: TambÃ©m aumenta seu ether_.

# _Qual seria o limite dos status?_
![alt text](image-23.png)
### _*Normalmente seria 75, mas Ã© possivel quebrar o limite de 75, fazendo o status chegar atÃ© 100, onde Ã© o â€œlimiteâ€ atual*_.
# HÃ¡ armas ou equipamentos que exigem status especÃ­ficos?
### _Sim, existem varios,como as armas pesadas, que exigem STR (forÃ§a), fora o status normais da sua arma, e algumas pedem status de attunements tambÃ©m._
### Ex: Pyrekeeper do personagem com cabelo verde na esquerda.
![alt text](image-24.png)
# _*Shrine of order:*_
![alt text](image-25.png)
### -_Tendo haver com os status, essa shrine faz o seguinte: Ela vai balancear seus status, fazendo os maior status diminuirem um pouco, e o mais baixos aumentarem, mas mesmo mudando os status, vocÃª vai continuar com os talentos que vocÃª pegou._
## *_Qual a importÃ¢ncia dela?_*
### *-Ela Ã© uma das coisas mais importante, pois usando ela, vocÃª consegue balancear seus status, e com o sistema de continuar com os talentos, deixa sua â€œbuildâ€ muito boa, fazendo a Shrine Of Order, uma das mais importantes de todo o jogo.*
## Existem outras Shrines?
## _-Sim, existem mais, porÃ©m cada uma com sua funÃ§Ã£o, mas nÃ£o estarÃ¡ explicado esse topico aqui._
# *_Vantagens e Desvantagens(Boons and Flaws)_*
### -_*Na criaÃ§Ã£o de personagem, podemos ter atÃ© duas vantagens, porÃ©m, Ã© obrigatÃ³rio ter duas desvantagens para isso.*_
![alt text](image-26.png)

## _-Quantas vantagens e desvantagens existem?_
### Atualmente existem:
### _9 Vantagens e 15 Desvantagens_

### _O resto estÃ¡ em desenvolvimento por motivos de: PreguiÃ§a do criador do guia._
![alt text](https://media.tenor.com/1rcgL2LQEQUAAAAM/deepwoken-owl.gif)

# _Origens:_ âšœ
## *_As origens sÃ£o onde vocÃª irÃ¡ nascer, sendo elas:_*
![alt text](image-27.png)
## _Castaway:_

### *_Em Castaway, vocÃª irÃ¡ nascer em Etris ou Isle of Vigils, duas cidades do jogo.(essa origem ja vem desde a compra do jogo)_*

## _Lone Warrior:_
### Atualmente, existem apenas uma opÃ§Ã£o em lone warrior, que Ã© nascer em minityrsa, tendo que fazer a  Trial Of One/Julgamento de Um
## Deepbound:
### Nascendo nas profundezas (The Depths), ganhando muito XP matando os monstros do loca, porÃ©m sendo uma das origens mais dificeis de se jogar.
## Voidwalker:
### Nascendo na superficie, em Knives of Eyles, vocÃª acaba sendo odiado por certas facÃ§Ãµes, como Etrea, e dependerÃ¡ de matar player.
## Ignition Delver:
### Sendo a origem mais recente, vocÃª irÃ¡ nascer na Union Ignition, uma das facÃ§Ãµes do jogo, localizada em Eastern Luminant.

# FIM.


### -Esse guia tem como obejtivo, ensinar, principalmente aos iniciantes do jogo, a terem uma experiÃªncia mais agradÃ¡vel, conhecendo um pouco sobre o jogo e suas mecÃ¢nicas, todas as imagem deste site foram retiradas da wiki oficial e algumas dos criadores do site e da internet. No mais Ã© isso. Valeu!










































  





[def]: image-1.png
